### PR TITLE
Component Router Core

### PR DESCRIPTION
**Pull request by nkbt**
I want to heavily simplify the API of the core to the bare minimum. And move other parts into separate components. Different modules may live in the same package, not necessarily split into multiple repos, thought it looks as a good idea to me to keep them all separately.

So at the moment I see it as:

## `component-router` core - package
  - [keep] Store
  - [keep] Actions
  - [keep] Reducers
  - [new] Container, new container component, that expects function as children and will call it passing `query`. Sort of:

    ```js
    <RouterContainer>
      {query => <MyComponent value={query.myComponent} />}
    </RouterContainer>
    ```

## `component-router-browser-history`
  - [keep] Location/Html5

## `component-router-hash-history`
  - [keep] Location/Html4

# Update 1

## `component-router` core - package
- Should not have React dependency. I want to use it within Angular app.
- [remove] Container, since it depends on react, it should go to a separate react package

# Update 2
There is no need for separate `component-router-browser-history` and `component-router-hash-history`, they are included into  the core.

### CODE REVIEW

**Comment by nkbt** [comment]
@halhenke bit too large to check and it is still WIP, though it already has a base working example to check.

**Comment by halhenke** [comment]
Cool! Will have a look when I get home

Good to see @ButenkoT getting into it :smiley:  :+1:

**Comment by halhenke** [comment]
Wow - theres a **lot** in here!

**Comment by nkbt** [comment]
Added:
- `href` to create href for links
- `isActive` to return if query is "active" (matches currently stored query in the store)
- `Url` react component (in example)
- `UrlContainer` react component (in example)

**Pull request merged**
